[package]
name = "calc"
version = "0.1.0"
edition = "2021"

[dependencies]
clier_parser = "0.7.3"
math = "0.11.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html