[package]
name = "calcer"
description = "Calcer is a nice program to write graphs from programs"
version = "0.2.1"
edition = "2021"
license = "MIT"
repository = "https://github.com/vincent-thomas/clier"

[dependencies]
clier = "0.7.3"
colored = "2.1.0"
